### ISSUE TITLE
Delphi example doesn't work

### ISSUE THREAD

**Issue by safwatbasha** [hshatti/TONNXRuntime#1]
when I run Delphi example it' compile ok but application does not work (message :)
![Capture](https://user-images.githubusercontent.com/50146687/222551353-353bb80f-893b-4256-82e0-c304562c6411.JPG)

**Comment by hshatti** [comment]
Hi, this could be an optimizer issue with Delphi Community Edition (10.4 Update 2) , try to rebuild the example (Shift - F9) instead of compiling and run again see if the problem is solved.
Cheers
H

**Comment by safwatbasha** [comment]
I'm using Delphi 11.1 . tried to rebuild and I have the same issue .

**Comment by hshatti** [comment]
There could be many reasons causing this issue, i don't know what environment you are using but here are some steps to check:
- The examples were tested on onnxruntime version 1.13.1, in case you are using Windows x64, download the library and place the dll's next to the output executable, you can find the library here:
   https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/onnxruntime-win-x64-1.13.1.zip
- the example runs on Windows 11 , x64 bit so make sure the onnx libraries and the example are build with 64 bit otherwise use the onnxruntime  relevant library
- the Delphi example uses an FMX project make sure your Delphi FMX libraries are installed or you can refere to the Lazarus project to build in VCL 
- always make sure to build the project before compiling to ensure all unit libraries were updated

Let me know if this works
Cheers
H

**Comment by safwatbasha** [comment]
working fine . thank you
