### ISSUE TITLE
call other ONNX models  error 

### ISSUE THREAD

**Issue by QuietMinder** [hshatti/TONNXRuntime#8]
I am trying to use the common.onnx and commondex.onnx models from the https://github.com/sml2h3/ddddocr repository for text detection and recognition tasks. However, I am encountering an error that says code[2]: NULL input supplied for input input1. I have tried calling them following the example of fastcnn, but I still get the same error. Could you please help me identify where the problem might be?

**Comment by hshatti** [comment]
Happy to help, i might need some further context on how do you use the model, i had a quick look at the python source but i wish I know mandarin to get some context, sharing your pascal code snippet that you are facing this issue with would help, however in short you 1st need to explore the models inputs and output shapes so you can construct the right shape of the tensors to feed the model with , the input NULL message can be caused by too many possibilities here could be a small fix
